# Generated by Django 3.2.25 on 2025-06-21 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distancePricecalcualtion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayBasedPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('base_distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('additional_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('waiting_charge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waiting_time_threshold', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingConfigLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.TextField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distancePricecalcualtion.pricingconfig')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_upper_bound', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.PositiveIntegerField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_multipliers', to='distancePricecalcualtion.pricingconfig')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('config', 'duration_upper_bound')},
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='daybasedpricing',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_pricing', to='distancePricecalcualtion.pricingconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='daybasedpricing',
            unique_together={('config', 'day')},
        ),
    ]
